# Generated by Django 2.2.1 on 2019-05-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('car', models.PositiveSmallIntegerField()),
                ('num_patrons', models.PositiveSmallIntegerField()),
                ('pickup', models.CharField(max_length=100)),
                ('dropoff', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('wait_begin', models.TimeField(auto_now_add=True)),
                ('waiting', models.BooleanField()),
                ('riding', models.BooleanField()),
                ('done', models.BooleanField()),
                ('deleted', models.BooleanField()),
            ],
        ),
    ]
