# Generated by Django 3.0.2 on 2020-01-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonelist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('car', models.PositiveSmallIntegerField()),
                ('num_patrons', models.PositiveSmallIntegerField()),
                ('pickup', models.CharField(max_length=100)),
                ('dropoff', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('waiting', models.BooleanField()),
                ('riding', models.BooleanField()),
                ('done', models.BooleanField()),
                ('cancelled', models.BooleanField()),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Patron',
        ),
    ]
