# Generated by Django 3.0.2 on 2020-01-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonelist', '0002_auto_20200116_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
