# Generated by Django 3.0.2 on 2020-01-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonelist', '0003_auto_20200116_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
