# Generated by Django 3.0.2 on 2020-01-16 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('phonelist', '0004_auto_20200116_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 6, 37, 24, 745474, tzinfo=utc)),
        ),
    ]
